import type { Metadata } from "next";

// Fonts
import { ubuntu } from "./fonts/index";

// Styles
import "@/css/globals.css";

export const metadata: Metadata = {
  title: "Viral burgers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
